name: Unit Tests
env:
  REACT_APP_ALCHEMY_ID: ${{ secrets.REACT_APP_ALCHEMY_ID }}

# Triggers the workflow on push or pull request events
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Copy .env vars
        run: cp .env.default .env
      - name: Set env
        run: echo "REACT_APP_ALCHEMY_ID=$(echo $REACT_APP_ALCHEMY_ID | cut -c 1-6)" >> $REACT_APP_ALCHEMY_ID
      - name: Install
        run: yarn
      - name: Run unit tests
        run: yarn hardhat & yarn test
