name: Unit Tests

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node version
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Copy .env vars
        run: cp .env.default .env
      - name: Install
        run: yarn
      - name: Run unit tests
        run: yarn test
